apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: depi-eks
  region: us-east-1
  version: "1.34"

vpc:
  cidr: "10.0.0.0/16"


nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    privateNetworking: true       
    ssh:
      allow: false                 
    iam:
      withAddonPolicies:
        autoScaler: false
        ebs: true                 
        fsx: false
        albIngress: false

iam:
  withOIDC: true
