apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: depi-eks
  region: us-east-1
  version: "1.34"

iam:
  withOIDC: true

vpc:
  cidr: "10.0.0.0/16"
  nat:
    gateway: HighlyAvailable

nodeGroups:
  - name: ng-workers-large
    instanceType: t3.large
    desiredCapacity: 3
    minSize: 3
    maxSize: 4
    privateNetworking: true
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        albIngress: true
    labels:
      eks.amazonaws.com/compute-type: "ec2"

  - name: bastion-ng
    instanceType: t3.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    privateNetworking: false
    ssh:
      allow: true
      publicKeyName: abeer-key-eks
    labels:
      role: bastion
    taints:
      - key: "bastion"
        value: "true"
        effect: "NoSchedule"


