pipeline {
  agent { label 'slave-node' }

  stages {

    stage('Check Jenkins commits') {
      steps {
        script {
          checkout scm
          def authorEmail = sh(returnStdout: true, script: "git show -s --format='%ae' HEAD").trim()
          def lastMsg = sh(returnStdout: true, script: "git log -1 --pretty=%B").trim()

          echo "Commit author: ${authorEmail}"
          echo "Commit message: ${lastMsg}"

          def jenkinsBotEmails = ['jenkins@example.com', 'actions@github.com']

          if (jenkinsBotEmails.contains(authorEmail) || lastMsg.contains('[ci skip]') || lastMsg.contains('[skip ci]')) {
            echo "Detected CI-created commit or skip token → skipping pipeline to avoid webhook loop."
            currentBuild.result = 'NOT_BUILT'
            return
          }
        }
      }
    }

    stage('Load Scripts') {
      when { expression { currentBuild.result != 'NOT_BUILT' } }
      steps {
        script {
          buildImage = load 'ci/steps/buildImage.groovy'
          scanImage = load 'ci/steps/scanImage.groovy'
          updateManifests = load 'ci/steps/updateManifests.groovy'
          pushManifests = load 'ci/steps/pushManifests.groovy'
        }
      }
    }

    stage('Pipeline Steps') {
      when { expression { currentBuild.result != 'NOT_BUILT' } }
      steps {
        script {
          buildImage()
          scanImage()
          updateManifests()
          pushManifests()
        }
      }
    }
  }
}
